analyze.py: add missing return statement
Also see issue #8 -- this might happen:

UnboundLocalError: local variable 'ename' referenced before assignment